yaml name: MatchaWatch 
on: 
schedule: - 
cron: '*/15 * * * *' 
workflow_dispatch: 
jobs: 
ping: 
runs-on: windows-latest 
steps: - 
uses: actions/checkout@v4 - 
name: Ejecutar script 
shell: pwsh 
env: TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }} TELEGRAM_CHATID: ${{ secrets.TELEGRAM_CHATID }} run: pwsh -File .\MatchaStockCheckerParams.ps1
